### ISSUE TITLE
correr comandos de mysql desde el docker-compose

### ISSUE THREAD

**Issue by DianaCato** [DianaCato/BOG002-burger-queen-api#1]
Tengo un archivo test.yml :

> version: "3"
> services:
>   db:
>    image: mysql:5
>    tmpfs:
>      - /var/lib/mysql
>    ports: 
>     - 23306:3306
>    environment:
>      MYSQL_ROOT_PASSWORD: supersecret
>      MYSQL_DATABASE: test
>      MYSQL_USER: test
>      MYSQL_PASSWORD: secret
> 
>    restart: always
>    networks:
>     - public
>     - private
> networks:
>   public:
>     internal: false
>   private:
>     internal: true

y luego tengo un archivo test.sql:

> CREATE DATABASE IF NOT EXISTS test;
> 
> USE test;
> 
> CREATE TABLE users (
>     id INT(11) NOT NULL AUTO_INCREMENT,
>     email VARCHAR(30) NOT NULL,
>     password VARCHAR(60) NOT NULL,
>     isAdmin TINYINT NULL DEFAULT 0 ;,
>     PRIMARY KEY (id)
> );

Quisiera poder correr los comandos de mysql cuando levanto el docker-compose, para no tener que hacerlo de manera manual.

He intentado agregando esta línea en mi test.yml:

`command: mysql -u root -p && supersecret && show databases`

Pero me sale el siguiente error : 

db_1  | Enter password: ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock

**Comment by CarlaSanchezCorrea** [comment]
Intentaría cambiar de puerto para el test. 😊

**Comment by DianaCato** [comment]
Lo solucione instalando "run-my-sql-file" y creando un script para correr los comandos sql de mi archivo
