### ISSUE TITLE
Guardar data anidada en mysql

### ISSUE THREAD

**Issue by DianaCato** [DianaCato/BOG002-burger-queen-api#3]
Estoy manejando mysql para almacenar la data, hasta el momento todo había ido bien, pero cuando llegué al endpoint de _orders_  me ha generado mucho conflicto recuperar la data que tenia almacenada, ya que utilice una llave foranea para tablas relacionadas con la información de la orden y la segunda con los productos del pedido. 

Estos son los comandos de mysql

> 
> CREATE TABLE orders (
>   _id INT NOT NULL AUTO_INCREMENT,
>   userId INT NOT NULL,
>   client VARCHAR(45) DEFAULT NULL,
>   status VARCHAR(45) NOT NULL,
>   dateEntry DATE NOT NULL,
>   dateProcessed DATE DEFAULT NULL,
>   PRIMARY KEY (_id),
>   INDEX userId_idx (userId ASC),
>   CONSTRAINT userId
>     FOREIGN KEY (userId)
>     REFERENCES test.users (_id)
>     ON DELETE CASCADE
>     ON UPDATE CASCADE);
> 
> CREATE TABLE `products_in_order` (
>   `id` int(11) NOT NULL AUTO_INCREMENT,
>   `id_order` int(11) NOT NULL,
>   `id_product` int(11) NOT NULL,
>   `qty` int(11) NOT NULL,
>   PRIMARY KEY (`id`),
>   KEY `id_order` (`id_order`),
>   KEY `id_product` (`id_product`),
>   CONSTRAINT `id_order` FOREIGN KEY (`id_order`) REFERENCES `orders` (`_id`) ON DELETE CASCADE ON UPDATE CASCADE,
>   CONSTRAINT `id_product` FOREIGN KEY (`id_product`) REFERENCES `products` (`_id`) ON DELETE CASCADE ON UPDATE CASCADE
> );
> 

Pero al traer la data con esta acción:

> SELECT userId, client, status, orders.dateEntry, dateProcessed, qty, name, price, imagen, type FROM orders 
>     INNER JOIN products_in_order ON orders._id = products_in_order.id_order 
>     INNER JOIN products ON products_in_order.id_product = products._id WHERE orders._id = ?

Obtengo un 404, porque no encutra rows

**Comment by Andy164** [comment]
El id para consultar el registro de la orden actualizada estaba harcodeado. Se hizo la corrección y los tests pasaron. Sin embargo es mejor volver a correr los tests para asegurar que este haya sido el error y no otro.
